client/app/build.gradle, client/app/src/main/AndroidManifest.xml, client/app/src/main/java/io/mosip/registration/app/MainActivity.java, client/app/src/main/java/io/mosip/registration/app/di/AppComponent.java, client/app/src/main/java/io/mosip/registration/app/di/AppModule.java, client/build.gradle, client/clientmanager/build.gradle, client/clientmanager/src/androidTest/java/io/mosip/registration/clientmanager/AndroidNetworkingTest.java, client/clientmanager/src/androidTest/java/io/mosip/registration/clientmanager/DaoTest.java, client/clientmanager/src/androidTest/java/io/mosip/registration/clientmanager/ExampleInstrumentedTest.java, client/clientmanager/src/main/AndroidManifest.xml, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/database/AuthDatabase.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/database/entities/UserToken.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/database/objectdao/UserTokenDao.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/crypto/SignRequestDto.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/http/RequestDTO.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/http/RequestDto.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/http/RequestWrapper.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/http/ResponseWrapper.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/http/ServiceError.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/crypto/LocalClientCryptoServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/RestService.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/advice/TestAdvice.java, client/clientmanager/src/main/res/xml/network_security_config.xml, client/settings.gradle
- FastAndroidNetworking functions have been added to io.mosip.registration.clientmanager.util.RestService. (few functions requiring additional defined classes commented out)
- Internet Permissions added to AndroidManifest.xml
- Added gradle-aspectj-pipeline-plugin 
- Sample AOP added to io.mosip.registration.clientmanager.util.advice.TestAdvice.
=> Fast Android Networking and AOP

client/app/src/main/java/io/mosip/registration/app/activites/AcknowledgementActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/ListingActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/PreviewActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/ScreenActivity.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/constant/AuditEvent.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/AuditManagerServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/AuditManagerService.java
Biometric capture failure audit logs added.
Module Id for dynamic registration screens updated.
Audit Logs https://technofortespl-my.sharepoint.com/:x:/g/personal/anshul_vanawat_onpalms_com/EQkECsIqjs1NihNVukflRbUBVanIxxjfRTyJRvUX8pNmzA?e=uaICDG
=> Audit updates MOSIP-22394

client/clientmanager/src/main/java/io/mosip/registration/clientmanager/config/AppModule.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/MasterDataServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/RegistrationServiceImpl.java, client/clientmanager/src/main/res/values/strings.xml
MOSIP-22707, application sync serialized and syncing master data recursively to fetch all required data at once.
MOSIP-22335 validation for no policy key in DB added for a new registration
=> Bug MOSIP-22707 and MOSIP-22335 fixed

client/app/src/main/AndroidManifest.xml, client/app/src/main/java/io/mosip/registration/app/ActivityBuildersModule.java, client/app/src/main/java/io/mosip/registration/app/activites/JobServiceActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/ListingActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/LoginActivity.java, client/app/src/main/java/io/mosip/registration/app/activites/MainActivity.java, client/app/src/main/java/io/mosip/registration/app/dynamicviews/DynamicDropDownBox.java, client/app/src/main/java/io/mosip/registration/app/viewmodel/JobServiceViewModel.java, client/clientmanager/src/androidTest/java/io/mosip/registration/clientmanager/MasterDataServiceImplTest.java, client/clientmanager/src/androidTest/java/io/mosip/registration/clientmanager/PacketServiceImplTest.java, client/clientmanager/src/main/AndroidManifest.xml, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/config/AppModule.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/jobs/ConfigDataSyncJob.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/jobs/PacketStatusSyncJob.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/jobs/SyncJobServiceBase.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/repository/SyncJobDefRepository.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/JobManagerServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/MasterDataServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/PacketServiceImpl.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/JobManagerService.java, client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/PacketService.java, client/clientmanager/src/main/res/values/strings.xml
MOSIP-22751 corrected,
JobSerivce helper updated as jobManagerService.
MOSIP-22758 corrected
=> MOSIP-22751 corrected

client/app/src/main/java/io/mosip/registration/app/dynamicviews/DynamicSwitchBox.java
Parameter FieldName in getFieldValues changed from id to subType, consistent with dynamic dropdown field
=> Parameter FieldName in getFieldValues changed from id to subType

client/app/src/main/java/io/mosip/registration/app/activites/RegistrationActivity.java
MOSIP-22780 Condition for enable disable next button updated
=> MOSIP-22780 Condition for enable disable next button updated

client/app/src/main/res/layout/dynamic_agedate_box.xml
MOSIP-22806 Date of birth layout re-arranged
=> MOSIP-22806 Date of birth layout re-arranged

android/app/src/main/java/io/mosip/registration_client/api_services/MasterDataSyncApi.java, lib/provider/sync_provider.dart, lib/ui/login_page.dart
Order of the auto sync is fixed, some UI bugs fixed as well.
=> auto sync order fixed

.github/workflows/build-android.yml, lib/ui/process_ui/new_process.dart
Bux fixes for introducer biometrics and changes for release build
=> Feature flutter

android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
=> Added a fix for null username

android/app/src/main/java/io/mosip/registration_client/api_services/DocumentDetailsApi.java, lib/l10n/app_ar.arb, lib/l10n/app_en.arb, lib/l10n/app_fr.arb, lib/l10n/app_hi.arb, lib/l10n/app_kn.arb, lib/l10n/app_ta.arb, lib/provider/global_provider.dart, lib/provider/registration_task_provider.dart, lib/ui/process_ui/widgets/document_upload_control.dart
@jainhitesh9998 please review the changes and merge.
[RCF-265]
[RCF-265]: https://mosip.atlassian.net/browse/RCF-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RCF-265] added delete functionality for document page

lib/ui/process_ui/widgets/date_control.dart
@jainhitesh9998 NIC date validation issue fixed [RCF-321]
[RCF-321]: https://mosip.atlassian.net/browse/RCF-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NIC date validation issue fixed

lib/ui/process_ui/widgets/textbox_control.dart
Fixed scroll issue in demographic page - [RCF-326]
[RCF-326]: https://mosip.atlassian.net/browse/RCF-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed scroll issue in demographic page

android/app/build.gradle, android/app/src/main/java/io/mosip/registration_client/api_services/CommonDetailsApi.java, android/build.gradle, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/repository/GlobalParamRepository.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/MasterDataServiceImpl.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/MasterDataService.java, android/settings.gradle, lib/model/actuator_info.dart, lib/platform_android/network_service_impl.dart, lib/platform_spi/network_service.dart, lib/provider/global_provider.dart, lib/ui/common/tablet_footer.dart, lib/ui/login_page.dart, pigeon/common_details.dart, pubspec.yaml
[RCF-314] - Added server version by calling actuator/info endpoint
[RCF-314]: https://mosip.atlassian.net/browse/RCF-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Save version to global params

lib/ui/process_ui/widgets/new_process_screen_content.dart, lib/ui/process_ui/widgets/textbox_control.dart, lib/utils/life_cycle_event_handler.dart
Fixed the text field hang issue on lock and unlock the device - [RCF-313].
[RCF-313]: https://mosip.atlassian.net/browse/RCF-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed the text field hang issue on lock and unlock the device.

lib/ui/post_registration/acknowledgement_page.dart, lib/ui/post_registration/preview_page.dart, pubspec.lock
[RCF-308] - bug fix for scrolling issue on preview and acknowledgement Page
[RCF-308]: https://mosip.atlassian.net/browse/RCF-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Navigation tab fix

android/clientmanager/src/main/res/values/strings.xml
[RCF-362] Change app id for audits.
[RCF-362]: https://mosip.atlassian.net/browse/RCF-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Changed appId for audit logs

android/app/src/main/java/io/mosip/registration_client/api_services/ProcessSpecDetailsApi.java
[RCF-322]
[RCF-322]: https://mosip.atlassian.net/browse/RCF-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed max language selection

lib/ui/process_ui/widgets/document_upload_control.dart
[RCF-300]
[RCF-300]: https://mosip.atlassian.net/browse/RCF-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> disabled scanned button based on user input

lib/provider/global_provider.dart, lib/ui/process_ui/widgets/age_date_control.dart, lib/ui/process_ui/widgets/custom_cupertino_picker.dart, lib/ui/process_ui/widgets/date_control.dart, lib/ui/process_ui/widgets/gender_control.dart, lib/ui/process_ui/widgets/new_process_screen_content.dart
[RCF-143](https://mosip.atlassian.net/browse/RCF-143) - Demographic screen gender, age-date, date control type updated.
[RCF-143]: https://mosip.atlassian.net/browse/RCF-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Demographics UI update

lib/ui/process_ui/new_process.dart
[RCF-376] Fixed
[RCF-376]: https://mosip.atlassian.net/browse/RCF-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RCF-376] Fixed

lib/l10n/app_ar.arb, lib/l10n/app_en.arb, lib/l10n/app_fr.arb, lib/l10n/app_hi.arb, lib/l10n/app_kn.arb, lib/l10n/app_ta.arb, lib/ui/process_ui/widgets/textbox_control.dart
[RCF-372](https://mosip.atlassian.net/browse/RCF-372) - Validation Message in textbox language
[RCF-372]: https://mosip.atlassian.net/browse/RCF-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> validation message in multiple language

lib/ui/process_ui/widgets/dropdown_control.dart, lib/ui/process_ui/widgets/dynamic_dropdown_control.dart, lib/ui/process_ui/widgets/gender_control.dart, lib/ui/process_ui/widgets/radio_button_control.dart
=> Values for all selected langauges added to dto

android/app/src/main/java/io/mosip/registration_client/MainActivity.java, android/build.gradle, lib/ui/onboard/home_page.dart, lib/ui/process_ui/widgets/age_date_control.dart, lib/ui/process_ui/widgets/date_control.dart, lib/ui/process_ui/widgets/dropdown_control.dart, lib/ui/process_ui/widgets/dynamic_dropdown_control.dart, lib/ui/process_ui/widgets/gender_control.dart, lib/ui/process_ui/widgets/textbox_control.dart
[RCF-372](https://mosip.atlassian.net/browse/RCF-372) - error message in Mandatory lang demographic screen
[RCF-403](https://mosip.atlassian.net/browse/RCF-403) - packet sync job triggered before packet upload job
[RCF-412](https://mosip.atlassian.net/browse/RCF-412) - batch job triggered at the scheduled time/interval
[RCF-391](https://mosip.atlassian.net/browse/RCF-391) - french transliteration as in Desktop reg client
[RCF-372]: https://mosip.atlassian.net/browse/RCF-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCF-403]: https://mosip.atlassian.net/browse/RCF-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCF-412]: https://mosip.atlassian.net/browse/RCF-412?atlOrigin=eyJpIjoiNWRkNTljN …
=> Minor bugs

lib/ui/process_ui/widgets/html_box_control.dart, lib/ui/process_ui/widgets/textbox_control.dart
[RCF-448](https://mosip.atlassian.net/browse/RCF-448)
[RCF-448]: https://mosip.atlassian.net/browse/RCF-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> text alignment for arabic

android/app/src/main/java/io/mosip/registration_client/MainActivity.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/constant/ClientManagerConstant.java
[RCF-438](https://mosip.atlassian.net/browse/RCF-438) - Packet batch job duplication request error fix
[RCF-447](https://mosip.atlassian.net/browse/RCF-447) - Auto batch job trigger multiple time
[RCF-438]: https://mosip.atlassian.net/browse/RCF-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCF-447]: https://mosip.atlassian.net/browse/RCF-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Auto batch job fix

lib/ui/process_ui/widgets/radio_button_control.dart, lib/ui/process_ui/widgets_mobile/biometric_capture_control_portrait.dart
[RCF-465]
[RCF-465]: https://mosip.atlassian.net/browse/RCF-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Radio Button Fix for Synergy Env [RCF-465]

pigeon.sh
=> script added in pigeon.sh

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/TemplateService.java
[RCF-399]
[RCF-399]: https://mosip.atlassian.net/browse/RCF-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-399 Resolved

lib/ui/process_ui/new_process.dart, lib/ui/process_ui/widgets/custom_label.dart, lib/ui/process_ui/widgets/document_upload_control.dart, lib/ui/process_ui/widgets/new_process_screen_content.dart
[RCF-496] Added null check conditions for null exceptions
[RCF-496]: https://mosip.atlassian.net/browse/RCF-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added null check conditions

.github/workflows/build-android.yml
Changed build action branch from feature-flutter to develop.
=> Changed build branch from feature-flutter to develop

lib/ui/process_ui/widgets/document_upload_control.dart, lib/ui/scanner/custom_scanner.dart
[RCF-401]
[RCF-401]: https://mosip.atlassian.net/browse/RCF-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-401 added event id for scan button and preview document

lib/ui/post_registration/acknowledgement_page.dart, lib/ui/process_ui/new_process.dart
[RCF-232] [RCF-402]
[RCF-232]: https://mosip.atlassian.net/browse/RCF-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCF-402]: https://mosip.atlassian.net/browse/RCF-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added back button functionality on registration screen

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/MasterDataServiceImpl.java, ios/Runner/pigeon.h, ios/Runner/pigeon.m, lib/ui/process_ui/widgets/document_upload_control.dart, lib/ui/process_ui/widgets/language_selector.dart
=> Fixed manual sync

lib/ui/onboard/home_page.dart, lib/ui/process_ui/widgets/document_upload_control.dart, lib/ui/process_ui/widgets/dropdown_control.dart, lib/ui/process_ui/widgets/dynamic_dropdown_control.dart, lib/ui/process_ui/widgets/textbox_control.dart
[RCF-556]
[RCF-556]: https://mosip.atlassian.net/browse/RCF-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed condtions for non-mandatory fields

assets/l10n/app_ar.arb, assets/l10n/app_en.arb, assets/l10n/app_fr.arb, assets/l10n/app_hi.arb, assets/l10n/app_kn.arb, assets/l10n/app_ta.arb, lib/provider/auth_provider.dart, lib/ui/login_page.dart, lib/ui/widgets/sync_alert_dialog.dart
[RCF-566] Alert Sync for reactivating machine or center.
[RCF-566]: https://mosip.atlassian.net/browse/RCF-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Alert sync added for inactive machine and center

android/app/src/main/java/io/mosip/registration_client/api_services/MasterDataSyncApi.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/MasterDataServiceImpl.java
Sync time updates on every successful attempt - [RCF-474](https://mosip.atlassian.net/browse/RCF-474)
[RCF-474]: https://mosip.atlassian.net/browse/RCF-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed RCF-474 reopened bug

lib/ui/process_ui/widgets/checkbox_control.dart
Fixed the checkbox selection in consent screen - [MOSIP-31856]
[MOSIP-31856]: https://mosip.atlassian.net/browse/MOSIP-31856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-31856]

android/app/src/main/java/io/mosip/registration_client/HostApiModule.java, android/app/src/main/java/io/mosip/registration_client/api_services/PacketAuthenticationApi.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/entity/Registration.java, lib/model/registration.dart, lib/platform_android/packet_service_impl.dart, lib/platform_spi/packet_service.dart, lib/provider/export_packet_provider.dart, lib/ui/export_packet/export_packet_ui.dart, lib/ui/export_packet/widgets/clear_dropdown_filter.dart, lib/ui/export_packet/widgets/client_status_dropdown.dart, lib/ui/export_packet/widgets/export_button.dart, lib/ui/export_packet/widgets/export_table.dart, lib/ui/export_packet/widgets/search_box.dart, lib/ui/export_packet/widgets/server_status_dropdown.dart, lib/ui/export_packet/widgets/upload_button.dart, lib/ui/onboard/home_page.dart, lib/utils/constants.dart, pigeon/packet_auth.dart
Bulk upload and export packets subtask - [RCF-640](https://mosip.atlassian.net/browse/RCF-640)
[RCF-640]: https://mosip.atlassian.net/browse/RCF-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-350 story

lib/ui/onboard/widgets/operator_biometric_capture_scan_block_view.dart, lib/ui/process_ui/widgets_mobile/biometric_capture_scan_block_portrait.dart
Alert dismiss fix in biometrics
=> Dialog-Fix

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/config/SessionManager.java
[RCF-788]
[RCF-788]: https://mosip.atlassian.net/browse/RCF-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Crash issue on logout fixed

.github/workflows/build-android.yml, android/app/build.gradle, lib/ui/onboard/home_page.dart
1. Release apk signing with mosip keys
2. Manual Trigger
=> Signing apk

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/config/AppModule.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/constant/RegistrationConstants.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/TemplateService.java
Added important guidelines to the template in develop.
=> [RCF-998D]

lib/ui/onboard/home_page.dart, lib/ui/process_ui/widgets/html_box_control.dart
Added order feature for the screens as per spec
=> [RCF-1087]

lib/ui/process_ui/widgets/language_selector.dart
Updated the guidelines logic in the language selector screen
=> [RCF-1077]

android/app/src/main/java/io/mosip/registration_client/api_services/BiometricsDetailsApi.java
Updated the biometrics error message
=> [RCF-1075]

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/repository/GlobalParamRepository.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/RegistrationServiceImpl.java
=> [RCF-991D]

lib/ui/process_ui/widgets/dropdown_control.dart, lib/ui/process_ui/widgets/dynamic_dropdown_control.dart
=> Dropdown value translate

android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/RegistrationServiceImpl.java
Added selected handles support for update flow-[RCF-1108]
[RCF-1108]: https://mosip.atlassian.net/browse/RCF-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RCF-1108]

lib/provider/global_provider.dart
[RCF-1107]
[RCF-1107]: https://mosip.atlassian.net/browse/RCF-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-1107-Z New Registration Biometric Screen Blank 

lib/provider/global_provider.dart
[RCF-1107]
[RCF-1107]: https://mosip.atlassian.net/browse/RCF-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-1107-Develop new registration biometric screen blank

lib/ui/process_ui/widgets/age_date_control.dart
Fixed the dob issue for security bug - [MOSIP-34420]
[MOSIP-34420]: https://mosip.atlassian.net/browse/MOSIP-34420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOSIP-34420]

lib/ui/process_ui/widgets/custom_dropdown_cupertino_picker.dart, lib/ui/process_ui/widgets/document_upload_control.dart
[RCF-1132]
[RCF-1132]: https://mosip.atlassian.net/browse/RCF-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RCF-1132] Dropdown values are not marked as selected.

lib/ui/approve_packet/widget/approve_table.dart, lib/ui/approve_packet/widget/template_bottom_sheet.dart
[RCF-1003] and [RCF-883]
[RCF-1003]: https://mosip.atlassian.net/browse/RCF-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RCF-883]: https://mosip.atlassian.net/browse/RCF-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-1003 and RCF-883

lib/ui/process_ui/widgets/custom_dropdown_cupertino_picker.dart, lib/ui/process_ui/widgets/document_upload_control.dart, lib/ui/process_ui/widgets/gender_control.dart
=> Rcf-1138 resolved revised preview data details issue

README.md
[RCF-1144]
[RCF-1144]: https://mosip.atlassian.net/browse/RCF-1144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RCF-1144] Updated README.md file

android/keymanager/build.gradle, android/keymanager/src/test/java/io/mosip/registration/keymanager/repository/CACertificateStoreRepositoryTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/service/CertificateDBHelperTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/service/CertificateManagerServiceImplTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/service/CryptoManagerServiceImplTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/service/LocalClientCryptoServiceImplTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/CertificateManagerUtilTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/ConfigServiceTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/CryptoUtilTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/DateUtilsTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/JsonUtilsTest.java, android/keymanager/src/test/java/io/mosip/registration/keymanager/util/KeyManagerConstantTest.java
[RCF-1149]
[RCF-1149]: https://mosip.atlassian.net/browse/RCF-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-1149 Unit test coverage keymanager module

android/app/src/main/java/io/mosip/registration_client/api_services/RegistrationApi.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/dto/registration/RegistrationDto.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/RegistrationServiceImpl.java, android/clientmanager/src/main/java/io/mosip/registration/clientmanager/service/TemplateService.java, lib/platform_android/registration_service_impl.dart, lib/platform_spi/registration_service.dart, lib/provider/registration_task_provider.dart, lib/ui/process_ui/widgets/pre_reg_data_control.dart, lib/ui/widgets/password_component.dart, pigeon/registration_data.dart
[RCF-1001]
[RCF-1001]: https://mosip.atlassian.net/browse/RCF-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-1001 pre-reg id number changes in preview and ack

ui-test/pom.xml
a security-related issue in the ui-test folder. Here is the link:
[android-registration-client/ui-test/pom.xml at release-0.12.x · mosip/android-registration-client](https://github.com/mosip/android-registration-client/blob/release-0.12.x/ui-test/pom.xml)
=> RCF-1176-Fixed Security testing: ARC: license compliance issue

android/build.gradle
Since the packet was not processing in the qa-core env, I changed the env to qa-base.
=> Changed env to qa-base

lib/ui/process_ui/widgets/pre_reg_data_control.dart
[RCF-856]
[RCF-856]: https://mosip.atlassian.net/browse/RCF-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> removed hardcoded label

lib/ui/process_ui/widgets_mobile/biometric_capture_scan_block_portrait.dart
[RCF-830]
[RCF-830]: https://mosip.atlassian.net/browse/RCF-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-830 fixed the overflow text

lib/ui/process_ui/widgets/custom_cupertino_picker.dart
[RCF-470]
[RCF-470]: https://mosip.atlassian.net/browse/RCF-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RCF-470 fixed date picker

lib/ui/approve_packet/widget/template_bottom_sheet.dart, lib/ui/dashboard/user_dashboard.dart, lib/ui/export_packet/export_packet_ui.dart
[RCF-472]
[RCF-472]: https://mosip.atlassian.net/browse/RCF-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UI fixes: pending approval dropdown, app upload, expand buttons, onboarding packet overflow

lib/ui/process_ui/lost_process.dart, lib/ui/process_ui/new_process.dart, lib/ui/process_ui/update_process.dart
[RCF-743]
[RCF-743]: https://mosip.atlassian.net/browse/RCF-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixed the issue removed the next arrow button when user is in last page-new ,lost and update reg 
